import { Feature } from '@a_ng_d/figmug-utils'

export const featuresScheme: Array<
  Feature<'BROWSE' | 'CREATE' | 'EDIT' | 'TRANSFER'>
> = [
  // Backstage
  {
    name: 'BACKSTAGE_ANALYTICS',
    description: 'Analytics for the ui',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'BACKSTAGE_MONITORING',
    description: 'Analytics for the palette',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'BACKSTAGE_AUTHENTICATION',
    description: 'User authentication module',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  // Services
  {
    name: 'BROWSE',
    description: 'Service for browsing palettes in the file',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'SERVICE',
    service: ['BROWSE'],
  },
  {
    name: 'CREATE',
    description:
      'Service for creating a palette when multiple colors are selected',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'SERVICE',
    service: ['CREATE'],
  },
  {
    name: 'EDIT',
    description: 'Service for configuring a palette when it is selected',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'SERVICE',
    service: ['EDIT'],
  },
  {
    name: 'TRANSFER',
    description: 'Service for transfering a palette into code',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'SERVICE',
    service: ['BROWSE', 'TRANSFER'],
  },
  {
    name: 'PROPERTIES',
    description: 'Provides shades information and WCAG scores',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'RESIZE_UI',
    description: 'Resizes the window',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT', 'BROWSE'],
  },
  // Modules
  {
    name: 'PUBLICATION',
    description: 'Palette publication pitch',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['EDIT'],
  },
  {
    name: 'PRO_PLAN',
    description: 'Pro plan subscription',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'USER_CONSENT',
    description: 'User vendors consent',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'NOTIFICATIONS',
    description: 'User notifications',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  // Contexts
  {
    name: 'LOCAL_PALETTES',
    description: 'Local palettes in the file',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['BROWSE'],
    limit: 5,
  },
  {
    name: 'LOCAL_PALETTES_PAGE',
    description: 'Saved palettes in the page',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['BROWSE'],
  },
  {
    name: 'REMOTE_PALETTES',
    description: 'Published palettes',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['BROWSE'],
  },
  {
    name: 'REMOTE_PALETTES_SELF',
    description: 'Self-created palettes',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['BROWSE'],
  },
  {
    name: 'REMOTE_PALETTES_COMMUNITY',
    description: 'Community-created palettes',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['BROWSE'],
  },
  {
    name: 'OPEN_PALETTE',
    description: 'Opens the palette',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'DUPLICATE_PALETTE',
    description: 'Duplicates the palette',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'DELETE_PALETTE',
    description: 'Deletes the palette',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'EDIT'],
  },
  {
    name: 'DOCUMENT_OPEN',
    description: 'Open document',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'DOCUMENT_CREATE',
    description: 'Create from the document',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SOURCE',
    description: 'Raw source colors',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['CREATE'],
    limit: 5,
  },
  {
    name: 'SOURCE_OVERVIEW',
    description: 'Overview and import of source colors',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['CREATE'],
  },
  {
    name: 'SOURCE_EXPLORE',
    description: 'External color palettes from Colour Lovers',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['CREATE'],
  },
  {
    name: 'SOURCE_CANVAS',
    description: 'Selected colors from the Figma or Figjam canvas',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE'],
  },
  {
    name: 'SOURCE_COOLORS',
    description: 'Import colors from a Coolors palette',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE'],
  },
  {
    name: 'SOURCE_REALTIME_COLORS',
    description: 'Import colors from a Realtime Colors simulation',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE'],
  },
  {
    name: 'SOURCE_COLOUR_LOVERS',
    description: 'Import colors from a Colour Lovers palette',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE'],
  },
  {
    name: 'SCALE',
    description: 'Lightness scale configuration',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SCALE_PRESETS',
    description: 'List of existing color systems',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['CREATE'],
  },
  {
    name: 'SCALE_PRESETS_NAMING_CONVENTION',
    description: 'Naming convention pattern',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE'],
  },
  {
    name: 'PRESETS_MATERIAL',
    description: 'Material Design color system',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'PRESETS_MATERIAL_3',
    description: 'Material 3 color system',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'PRESETS_TAILWIND',
    description: 'Tailwind color system',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'PRESETS_ANT',
    description: 'Ant Design color system',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'PRESETS_ADS',
    description: 'ADS Foundation color system',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'PRESETS_ADS_NEUTRAL',
    description: 'ADS Foundation Neutral color system',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'PRESETS_CARBON',
    description: 'IBM Carbon color system',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'PRESETS_BASE',
    description: 'Uber Base color system',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'PRESETS_POLARIS',
    description: 'Shopify Polaris color system',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'PRESETS_CUSTOM_1_10',
    description: 'Customized color system (1-10)',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'PRESETS_CUSTOM_10_100',
    description: 'Customized color system (10-100)',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'PRESETS_CUSTOM_100_1000',
    description: 'Customized color system (100-1000)',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'PRESETS_CUSTOM_ADD',
    description: 'New stop for the customized color system',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
    limit: 10,
  },
  {
    name: 'SCALE_CONFIGURATION',
    description: 'Lightness stops on a range slider',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SCALE_CONTRAST_RATIO',
    description: 'Contrast ratio configuration',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SCALE_CHROMA',
    description: 'Chroma scale configuration',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SCALE_HELPER',
    description: 'Tips and tools to help configure the scaling',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SCALE_HELPER_DISTRIBUTION',
    description: 'Distribution mode according to easings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SCALE_HELPER_DISTRIBUTION_LINEAR',
    description: 'Linear distribution mode',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SCALE_HELPER_DISTRIBUTION_EASE_IN',
    description: 'Ease-in distribution mode',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SCALE_HELPER_DISTRIBUTION_EASE_OUT',
    description: 'Ease-out distribution mode',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SCALE_HELPER_DISTRIBUTION_EASE_IN_OUT',
    description: 'Ease-in-out distribution mode',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SCALE_HELPER_DISTRIBUTION_SINE',
    description: 'Sine distribution mode',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SCALE_HELPER_DISTRIBUTION_QUAD',
    description: 'Quad distribution mode',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SCALE_HELPER_DISTRIBUTION_CUBIC',
    description: 'Cubic distribution mode',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SCALE_HELPER_TIPS',
    description: 'Keyboard shortcuts for scaling',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'COLORS',
    description: 'Configuration of source colors',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['EDIT'],
    limit: 5,
  },
  {
    name: 'COLORS_NAME',
    description: 'Name of the source color',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'COLORS_PARAMS',
    description: 'Parameters of the source color (hex and lch)',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'COLORS_HUE_SHIFTING',
    description: 'Hue shifting value for the source color',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'COLORS_CHROMA_SHIFTING',
    description: 'Chroma shifting value for the source color',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'COLORS_DESCRIPTION',
    description: 'Description of the source color purpose',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'COLORS_ALPHA',
    description: 'Alpha of the source color',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'COLORS_BACKGROUND_COLOR',
    description: 'Background color of the source color',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'THEMES',
    description: 'Configuration of color themes',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['EDIT'],
  },
  {
    name: 'THEMES_NAME',
    description: 'Name of the color theme',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'THEMES_PARAMS',
    description: 'Palette background related to the theme',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'THEMES_DESCRIPTION',
    description: 'Description of the color theme purpose',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'EXPORT',
    description: 'Options for exporting the palette',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_TOKENS',
    description: 'Export the palette to a tokens file',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_TOKENS_JSON',
    description: 'Export the palette to JSON format',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_TOKENS_JSON_AMZN_STYLE_DICTIONARY',
    description: 'Export the palette for Amazon Style Dictionary',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_TOKENS_JSON_TOKENS_STUDIO',
    description: 'Export the palette to Tokens Studio plugin',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_TOKENS_JSON_DTCG',
    description: 'Export the palette to DTCG format',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_TOKENS_JSON_DTCG_RGB',
    description: 'Export the palette to DTCG format (RGB)',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_TOKENS_JSON_DTCG_OKLCH',
    description: 'Export the palette to DTCG format (OKLCH)',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_CSS',
    description: 'Export the palette to CSS',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_CSS_RGB',
    description: 'Export the palette to CSS (RGB)',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_CSS_HEX',
    description: 'Export the palette to CSS (Hex)',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_CSS_HSL',
    description: 'Export the palette to CSS (HSL)',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_CSS_LCH',
    description: 'Export the palette to CSS (LCH)',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_CSS_P3',
    description: 'Export the palette to CSS (P3)',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_TAILWIND',
    description: 'Export the palette to Tailwind',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_APPLE',
    description: 'Export the palette for Apple projects',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_APPLE_SWIFTUI',
    description: 'Export the palette to SwiftUI (Apple)',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_APPLE_UIKIT',
    description: 'Export the palette to UIkit (Apple)',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_ANDROID',
    description: 'Export the palette for Android projects',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_ANDROID_COMPOSE',
    description: 'Export the palette to Compose (Android)',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_ANDROID_XML',
    description: 'Export the palette to XML (Android)',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'EXPORT_CSV',
    description: 'Export the palette LCH values to CSV',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['TRANSFER'],
  },
  {
    name: 'SETTINGS',
    description: 'General configuration settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_GLOBAL',
    description: 'Global configuration settings for the palette',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_NAME',
    description: 'Palette name settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_DESCRIPTION',
    description: 'Palette description settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'VIEWS',
    description: 'Configuration of palette views',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'VIEWS_PALETTE',
    description: 'Simple view of the palette',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'VIEWS_PALETTE_WITH_PROPERTIES',
    description: 'Detailed view of the palette with properties',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'VIEWS_SHEET',
    description: 'Detailed view of the color sheet',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_COLOR_MANAGEMENT',
    description: 'Configuration for palette color management',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_COLOR_SPACE',
    description: 'Global color space configuration for the palette',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_COLOR_SPACE_LCH',
    description: 'LCH color space settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_COLOR_SPACE_OKLCH',
    description: 'OKLCH color space settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_COLOR_SPACE_LAB',
    description: 'CIELAB color space settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_COLOR_SPACE_OKLAB',
    description: 'OKLAB color space settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_COLOR_SPACE_HSL',
    description: 'HSL color space settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_COLOR_SPACE_HSLUV',
    description: 'HSLUV color space settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_VISION_SIMULATION_MODE',
    description: 'Configuration for color blind simulation mode',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_VISION_SIMULATION_MODE_NONE',
    description: 'No vision simulation mode settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_VISION_SIMULATION_MODE_PROTANOMALY',
    description: 'Protanomaly vision simulation mode settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_VISION_SIMULATION_MODE_PROTANOPIA',
    description: 'Protanopia vision simulation mode settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOMALY',
    description: 'Deuteranomaly vision simulation mode settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOPIA',
    description: 'Deuteranopia vision simulation mode settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_VISION_SIMULATION_MODE_TRITANOMALY',
    description: 'Tritanomaly vision simulation mode settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_VISION_SIMULATION_MODE_TRITANOPIA',
    description: 'Tritanopia vision simulation mode settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOMALY',
    description: 'Achromatomaly vision simulation mode settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOPSIA',
    description: 'Achromatopsia vision simulation mode settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_ALGORITHM',
    description: 'Color shades generation algorithm settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'SETTINGS_ALGORITHM_V1',
    description:
      'First version of the color shades generation algorithm settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'SETTINGS_ALGORITHM_V2',
    description:
      'Second version of the color shades generation algorithm settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'SETTINGS_ALGORITHM_V3',
    description:
      'Third version of the color shades generation algorithm settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'SETTINGS_CONTRAST_MANAGEMENT',
    description: 'Configuration for palette contrast management',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'SETTINGS_TEXT_COLORS_THEME',
    description: 'Text colors customization settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'ACTIONS',
    description: 'Controls of the palette',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'CREATE_PALETTE',
    description: 'Generates a palette',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE'],
  },
  {
    name: 'SYNC_LOCAL_STYLES',
    description: 'Synchronizes local styles',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'SYNC_LOCAL_VARIABLES',
    description: 'Synchronizes local variables',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'PUBLISH_PALETTE',
    description: 'Publishes the palette to the community and self',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'DOCUMENT',
    description: 'Generates a document',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'DOCUMENT_SHEET',
    description: 'Generates a color sheet document',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'DOCUMENT_PALETTE',
    description: 'Generates a color palette document',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'DOCUMENT_PALETTE_PROPERTIES',
    description: 'Generates a color palette document with properties',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'DOCUMENT_PUSH_UPDATES',
    description: 'Pushes updates to the document',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['EDIT'],
  },
  {
    name: 'PREVIEW',
    description: 'Quick glance at the palette',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'PREVIEW_SCORES',
    description: 'Displays palette preview scores',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'PREVIEW_SCORES_WCAG',
    description: 'Displays WCAG scores for preview',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'PREVIEW_SCORES_APCA',
    description: 'Displays APCA scores for preview',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  {
    name: 'PREVIEW_LOCK_SOURCE_COLORS',
    description: 'Locks source colors in preview',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['CREATE', 'EDIT'],
  },
  // Shortcuts
  {
    name: 'SHORTCUTS',
    description: 'Quick useful links',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'USER',
    description: 'User menu',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'USER_PREFERENCES',
    description: 'User preferences settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'USER_PREFERENCES_SYNC_DEEP_STYLES',
    description: 'Deep synchronization of styles',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'CREATE', 'EDIT'],
  },
  {
    name: 'USER_PREFERENCES_SYNC_DEEP_VARIABLES',
    description: 'Deep synchronization of variables',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'CREATE', 'EDIT'],
  },
  {
    name: 'USER_LICENSE',
    description: 'License management module',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'HELP_ANNOUNCEMENTS',
    description: 'Release notes',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'HELP_ONBOARDING',
    description: 'Onboarding',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'HELP_DOCUMENTATION',
    description: 'User documentation',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'INVOLVE_REPOSITORY',
    description: 'Repository',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'HELP_EMAIL',
    description: 'Email support',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'HELP_CHAT',
    description: 'Chat support',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'INVOLVE_FEEDBACK',
    description: 'NPS and feedback form',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'INVOLVE_ISSUES',
    description: 'Bug reports',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'INVOLVE_COMMUNITY',
    description: 'Community discussions',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'INVOLVE_REQUESTS',
    description: 'Feature requests',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'MORE_STORE',
    description: 'Other products and services',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'MORE_ABOUT',
    description: 'Additional information',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'MORE_NETWORK',
    description: 'Social networks',
    isActive: false,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
  {
    name: 'MORE_AUTHOR',
    description: 'Author page',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'CREATE', 'EDIT', 'TRANSFER'],
  },
]

export const doSpecificMode = (
  unactiveFeature: Array<string>,
  proFeature?: Array<string>,
  newFeature?: Array<string>
) => {
  const features = featuresScheme.map((feature) => ({ ...feature }))
  const unactiveFeatures = new Set(unactiveFeature)
  const proFeatures = new Set(proFeature)
  const newFeatures = new Set(newFeature)

  return features.map((feature) => {
    if (unactiveFeatures.has(feature.name)) feature.isActive = false
    if (proFeatures.has(feature.name)) feature.isPro = true
    if (newFeatures.has(feature.name)) feature.isNew = true

    return feature
  })
}
