import { Feature } from '@a_ng_d/figmug-utils'
import { Config } from './types/config'
import { doSpecificMode } from './stores/features'

declare const __PLATFORM__: 'figma' | 'penpot' | 'sketch' | 'framer'
declare const __COLOR_MODE__: 'dark' | 'light'
declare const __EDITOR__: 'figma' | 'dev' | 'penpot' | 'framer'

const isDev = import.meta.env.MODE === 'development'
declare const __APP_VERSION__: string

interface SpecConfig {
  [platform: string]: {
    [colorMode: string]: {
      [editor: string]: {
        env: {
          platform: 'figma' | 'penpot' | 'sketch' | 'framer'
          editor: 'figma' | 'dev' | 'penpot' | 'sketch' | 'framer'
          ui: 'figma' | 'penpot' | 'sketch' | 'framer'
          colorMode:
            | 'figma-light'
            | 'figma-dark'
            | 'penpot-light'
            | 'penpot-dark'
            | 'sketch-light'
            | 'sketch-dark'
            | 'framer-light'
            | 'framer-dark'
        }
        features: Array<Feature<'BROWSE' | 'CREATE' | 'EDIT' | 'SEE'>>
      }
    }
  }
}

const specConfig: SpecConfig = {
  figma: {
    light: {
      figma: {
        env: {
          platform: 'figma',
          editor: 'figma',
          ui: 'figma',
          colorMode: 'figma-light',
        },
        features: doSpecificMode(
          ['LOCAL_PALETTES_FILE'],
          [
            'LOCAL_PALETTES',
            'SYNC_LOCAL_STYLES',
            'SYNC_LOCAL_VARIABLES',
            'USER_PREFERENCES_SYNC_DEEP_STYLES',
            'USER_PREFERENCES_SYNC_DEEP_VARIABLES',
            'PREVIEW_LOCK_SOURCE_COLORS',
            'DOCUMENT_PALETTE',
            'DOCUMENT_PALETTE_PROPERTIES',
            'DOCUMENT_SHEET',
            'DOCUMENT_PUSH_UPDATES',
            'VIEWS_PALETTE',
            'VIEWS_PALETTE_WITH_PROPERTIES',
            'VIEWS_SHEET',
            'SOURCE',
            'SOURCE_COOLORS_ADD',
            'SOURCE_REALTIME_COLORS_ADD',
            'SOURCE_EXPLORE_ADD',
            'SOURCE_AI_REQUEST',
            'SOURCE_IMAGE_UPLOAD',
            'SOURCE_HARMONY_BASE',
            'SOURCE_HARMONY_ADD',
            'SOURCE_EXPLORE_ADD',
            'PRESETS_CUSTOM_ADD',
            'SCALE_CHROMA',
            'THEMES',
            'THEMES_NAME',
            'THEMES_PARAMS',
            'THEMES_DESCRIPTION',
            'COLORS',
            'COLORS_HUE_SHIFTING',
            'COLORS_CHROMA_SHIFTING',
            'COLORS_ALPHA',
            'COLORS_BACKGROUND_COLOR',
            'EXPORT_STYLESHEET_SCSS',
            'EXPORT_STYLESHEET_LESS',
            'EXPORT_TAILWIND_V3',
            'EXPORT_TAILWIND_V4',
            'EXPORT_APPLE_SWIFTUI',
            'EXPORT_APPLE_UIKIT',
            'EXPORT_ANDROID_COMPOSE',
            'EXPORT_ANDROID_XML',
            'EXPORT_CSV',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOPSIA',
          ],
          []
        ),
      },
      dev: {
        env: {
          platform: 'figma',
          editor: 'dev',
          ui: 'figma',
          colorMode: 'figma-light',
        },
        features: doSpecificMode(
          ['LOCAL_PALETTES_FILE'],
          [
            'LOCAL_PALETTES',
            'SYNC_LOCAL_STYLES',
            'SYNC_LOCAL_VARIABLES',
            'USER_PREFERENCES_SYNC_DEEP_STYLES',
            'USER_PREFERENCES_SYNC_DEEP_VARIABLES',
            'PREVIEW_LOCK_SOURCE_COLORS',
            'DOCUMENT_PALETTE',
            'DOCUMENT_PALETTE_PROPERTIES',
            'DOCUMENT_SHEET',
            'DOCUMENT_PUSH_UPDATES',
            'VIEWS_PALETTE',
            'VIEWS_PALETTE_WITH_PROPERTIES',
            'VIEWS_SHEET',
            'SOURCE',
            'SOURCE_COOLORS_ADD',
            'SOURCE_REALTIME_COLORS_ADD',
            'SOURCE_EXPLORE_ADD',
            'SOURCE_AI_REQUEST',
            'SOURCE_IMAGE_UPLOAD',
            'SOURCE_HARMONY_BASE',
            'SOURCE_HARMONY_ADD',
            'SOURCE_EXPLORE_ADD',
            'PRESETS_CUSTOM_ADD',
            'SCALE_CHROMA',
            'THEMES',
            'THEMES_NAME',
            'THEMES_PARAMS',
            'THEMES_DESCRIPTION',
            'COLORS',
            'COLORS_HUE_SHIFTING',
            'COLORS_CHROMA_SHIFTING',
            'COLORS_ALPHA',
            'COLORS_BACKGROUND_COLOR',
            'EXPORT_STYLESHEET_SCSS',
            'EXPORT_STYLESHEET_LESS',
            'EXPORT_TAILWIND_V3',
            'EXPORT_TAILWIND_V4',
            'EXPORT_APPLE_SWIFTUI',
            'EXPORT_APPLE_UIKIT',
            'EXPORT_ANDROID_COMPOSE',
            'EXPORT_ANDROID_XML',
            'EXPORT_CSV',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOPSIA',
          ],
          []
        ),
      },
    },
    dark: {
      figma: {
        env: {
          platform: 'figma',
          editor: 'figma',
          ui: 'figma',
          colorMode: 'figma-dark',
        },
        features: doSpecificMode(
          ['LOCAL_PALETTES_FILE'],
          [
            'LOCAL_PALETTES',
            'SYNC_LOCAL_STYLES',
            'SYNC_LOCAL_VARIABLES',
            'USER_PREFERENCES_SYNC_DEEP_STYLES',
            'USER_PREFERENCES_SYNC_DEEP_VARIABLES',
            'PREVIEW_LOCK_SOURCE_COLORS',
            'DOCUMENT_PALETTE',
            'DOCUMENT_PALETTE_PROPERTIES',
            'DOCUMENT_SHEET',
            'DOCUMENT_PUSH_UPDATES',
            'VIEWS_PALETTE',
            'VIEWS_PALETTE_WITH_PROPERTIES',
            'VIEWS_SHEET',
            'SOURCE',
            'SOURCE_COOLORS_ADD',
            'SOURCE_REALTIME_COLORS_ADD',
            'SOURCE_EXPLORE_ADD',
            'SOURCE_AI_REQUEST',
            'SOURCE_IMAGE_UPLOAD',
            'SOURCE_HARMONY_BASE',
            'SOURCE_HARMONY_ADD',
            'SOURCE_EXPLORE_ADD',
            'PRESETS_CUSTOM_ADD',
            'SCALE_CHROMA',
            'THEMES',
            'THEMES_NAME',
            'THEMES_PARAMS',
            'THEMES_DESCRIPTION',
            'COLORS',
            'COLORS_HUE_SHIFTING',
            'COLORS_CHROMA_SHIFTING',
            'COLORS_ALPHA',
            'COLORS_BACKGROUND_COLOR',
            'EXPORT_STYLESHEET_SCSS',
            'EXPORT_STYLESHEET_LESS',
            'EXPORT_TAILWIND_V3',
            'EXPORT_TAILWIND_V4',
            'EXPORT_APPLE_SWIFTUI',
            'EXPORT_APPLE_UIKIT',
            'EXPORT_ANDROID_COMPOSE',
            'EXPORT_ANDROID_XML',
            'EXPORT_CSV',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOPSIA',
          ],
          []
        ),
      },
      dev: {
        env: {
          platform: 'figma',
          editor: 'dev',
          ui: 'figma',
          colorMode: 'figma-dark',
        },
        features: doSpecificMode(
          ['LOCAL_PALETTES_FILE'],
          [
            'LOCAL_PALETTES',
            'SYNC_LOCAL_STYLES',
            'SYNC_LOCAL_VARIABLES',
            'USER_PREFERENCES_SYNC_DEEP_STYLES',
            'USER_PREFERENCES_SYNC_DEEP_VARIABLES',
            'PREVIEW_LOCK_SOURCE_COLORS',
            'DOCUMENT_PALETTE',
            'DOCUMENT_PALETTE_PROPERTIES',
            'DOCUMENT_SHEET',
            'DOCUMENT_PUSH_UPDATES',
            'VIEWS_PALETTE',
            'VIEWS_PALETTE_WITH_PROPERTIES',
            'VIEWS_SHEET',
            'SOURCE',
            'SOURCE_COOLORS_ADD',
            'SOURCE_REALTIME_COLORS_ADD',
            'SOURCE_EXPLORE_ADD',
            'SOURCE_AI_REQUEST',
            'SOURCE_IMAGE_UPLOAD',
            'SOURCE_HARMONY_BASE',
            'SOURCE_HARMONY_ADD',
            'SOURCE_EXPLORE_ADD',
            'PRESETS_CUSTOM_ADD',
            'SCALE_CHROMA',
            'THEMES',
            'THEMES_NAME',
            'THEMES_PARAMS',
            'THEMES_DESCRIPTION',
            'COLORS',
            'COLORS_HUE_SHIFTING',
            'COLORS_CHROMA_SHIFTING',
            'COLORS_ALPHA',
            'COLORS_BACKGROUND_COLOR',
            'EXPORT_STYLESHEET_SCSS',
            'EXPORT_STYLESHEET_LESS',
            'EXPORT_TAILWIND_V3',
            'EXPORT_APPLE_SWIFTUI',
            'EXPORT_APPLE_UIKIT',
            'EXPORT_ANDROID_COMPOSE',
            'EXPORT_ANDROID_XML',
            'EXPORT_CSV',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOPSIA',
          ],
          []
        ),
      },
    },
  },
  penpot: {
    light: {
      penpot: {
        env: {
          platform: 'penpot',
          editor: 'penpot',
          ui: 'penpot',
          colorMode: 'penpot-light',
        },
        features: doSpecificMode(
          [
            'SYNC_LOCAL_VARIABLES',
            'USER_PREFERENCES_SYNC_DEEP_VARIABLES',
            'BACKSTAGE_AUTHENTICATION',
            'PUBLICATION',
            'PUBLISH_PALETTE',
            'REMOTE_PALETTES',
            'LOCAL_PALETTES_FILE',
          ],
          [
            'LOCAL_PALETTES',
            'SYNC_LOCAL_STYLES',
            'USER_PREFERENCES_SYNC_DEEP_STYLES',
            'PREVIEW_LOCK_SOURCE_COLORS',
            'DOCUMENT_PALETTE',
            'DOCUMENT_PALETTE_PROPERTIES',
            'DOCUMENT_SHEET',
            'DOCUMENT_PUSH_UPDATES',
            'VIEWS_PALETTE',
            'VIEWS_PALETTE_WITH_PROPERTIES',
            'VIEWS_SHEET',
            'SOURCE',
            'SOURCE_COOLORS_ADD',
            'SOURCE_REALTIME_COLORS_ADD',
            'SOURCE_EXPLORE_ADD',
            'SOURCE_AI_REQUEST',
            'SOURCE_IMAGE_UPLOAD',
            'SOURCE_HARMONY_BASE',
            'SOURCE_HARMONY_ADD',
            'SOURCE_EXPLORE_ADD',
            'PRESETS_CUSTOM_ADD',
            'SCALE_CHROMA',
            'THEMES',
            'THEMES_NAME',
            'THEMES_PARAMS',
            'THEMES_DESCRIPTION',
            'COLORS',
            'COLORS_HUE_SHIFTING',
            'COLORS_CHROMA_SHIFTING',
            'COLORS_ALPHA',
            'COLORS_BACKGROUND_COLOR',
            'EXPORT_STYLESHEET_SCSS',
            'EXPORT_STYLESHEET_LESS',
            'EXPORT_TAILWIND_V3',
            'EXPORT_TAILWIND_V4',
            'EXPORT_APPLE_SWIFTUI',
            'EXPORT_APPLE_UIKIT',
            'EXPORT_ANDROID_COMPOSE',
            'EXPORT_ANDROID_XML',
            'EXPORT_CSV',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOPSIA',
          ],
          []
        ),
      },
    },
    dark: {
      penpot: {
        env: {
          platform: 'penpot',
          editor: 'penpot',
          ui: 'penpot',
          colorMode: 'penpot-dark',
        },
        features: doSpecificMode(
          [
            'SYNC_LOCAL_VARIABLES',
            'USER_PREFERENCES_SYNC_DEEP_VARIABLES',
            'BACKSTAGE_AUTHENTICATION',
            'PUBLICATION',
            'PUBLISH_PALETTE',
            'REMOTE_PALETTES',
            'LOCAL_PALETTES_FILE',
          ],
          [
            'LOCAL_PALETTES',
            'SYNC_LOCAL_STYLES',
            'USER_PREFERENCES_SYNC_DEEP_STYLES',
            'PREVIEW_LOCK_SOURCE_COLORS',
            'DOCUMENT_PALETTE',
            'DOCUMENT_PALETTE_PROPERTIES',
            'DOCUMENT_SHEET',
            'DOCUMENT_PUSH_UPDATES',
            'VIEWS_PALETTE',
            'VIEWS_PALETTE_WITH_PROPERTIES',
            'VIEWS_SHEET',
            'SOURCE',
            'SOURCE_COOLORS_ADD',
            'SOURCE_REALTIME_COLORS_ADD',
            'SOURCE_EXPLORE_ADD',
            'SOURCE_AI_REQUEST',
            'SOURCE_IMAGE_UPLOAD',
            'SOURCE_HARMONY_BASE',
            'SOURCE_HARMONY_ADD',
            'SOURCE_EXPLORE_ADD',
            'PRESETS_CUSTOM_ADD',
            'SCALE_CHROMA',
            'THEMES',
            'THEMES_NAME',
            'THEMES_PARAMS',
            'THEMES_DESCRIPTION',
            'COLORS',
            'COLORS_HUE_SHIFTING',
            'COLORS_CHROMA_SHIFTING',
            'COLORS_ALPHA',
            'COLORS_BACKGROUND_COLOR',
            'EXPORT_STYLESHEET_SCSS',
            'EXPORT_STYLESHEET_LESS',
            'EXPORT_TAILWIND_V3',
            'EXPORT_TAILWIND_V4',
            'EXPORT_APPLE_SWIFTUI',
            'EXPORT_APPLE_UIKIT',
            'EXPORT_ANDROID_COMPOSE',
            'EXPORT_ANDROID_XML',
            'EXPORT_CSV',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOPSIA',
          ],
          ['SOURCE_AI', 'SOURCE_IMAGE', 'SOURCE_HARMONY']
        ),
      },
    },
  },
  sketch: {
    light: {
      sketch: {
        env: {
          platform: 'sketch',
          editor: 'sketch',
          ui: 'sketch',
          colorMode: 'sketch-light',
        },
        features: doSpecificMode(
          ['LOCAL_PALETTES_PAGE'],
          [
            'LOCAL_PALETTES',
            'SYNC_LOCAL_STYLES',
            'SYNC_LOCAL_VARIABLES',
            'USER_PREFERENCES_SYNC_DEEP_STYLES',
            'USER_PREFERENCES_SYNC_DEEP_VARIABLES',
            'PREVIEW_LOCK_SOURCE_COLORS',
            'DOCUMENT_PALETTE',
            'DOCUMENT_PALETTE_PROPERTIES',
            'DOCUMENT_SHEET',
            'DOCUMENT_PUSH_UPDATES',
            'VIEWS_PALETTE',
            'VIEWS_PALETTE_WITH_PROPERTIES',
            'VIEWS_SHEET',
            'SOURCE',
            'SOURCE_COOLORS_ADD',
            'SOURCE_REALTIME_COLORS_ADD',
            'SOURCE_EXPLORE_ADD',
            'SOURCE_AI_REQUEST',
            'SOURCE_IMAGE_UPLOAD',
            'SOURCE_HARMONY_BASE',
            'SOURCE_HARMONY_ADD',
            'SOURCE_EXPLORE_ADD',
            'PRESETS_CUSTOM_ADD',
            'SCALE_CHROMA',
            'THEMES',
            'THEMES_NAME',
            'THEMES_PARAMS',
            'THEMES_DESCRIPTION',
            'COLORS',
            'COLORS_HUE_SHIFTING',
            'COLORS_CHROMA_SHIFTING',
            'COLORS_ALPHA',
            'COLORS_BACKGROUND_COLOR',
            'EXPORT_TAILWIND_V3',
            'EXPORT_TAILWIND_V4',
            'EXPORT_APPLE_SWIFTUI',
            'EXPORT_APPLE_UIKIT',
            'EXPORT_ANDROID_COMPOSE',
            'EXPORT_ANDROID_XML',
            'EXPORT_CSV',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOPSIA',
          ],
          []
        ),
      },
    },
    dark: {
      sketch: {
        env: {
          platform: 'sketch',
          editor: 'sketch',
          ui: 'sketch',
          colorMode: 'sketch-dark',
        },
        features: doSpecificMode(
          ['LOCAL_PALETTES_PAGE'],
          [
            'LOCAL_PALETTES',
            'SYNC_LOCAL_STYLES',
            'SYNC_LOCAL_VARIABLES',
            'USER_PREFERENCES_SYNC_DEEP_STYLES',
            'USER_PREFERENCES_SYNC_DEEP_VARIABLES',
            'PREVIEW_LOCK_SOURCE_COLORS',
            'DOCUMENT_PALETTE',
            'DOCUMENT_PALETTE_PROPERTIES',
            'DOCUMENT_SHEET',
            'DOCUMENT_PUSH_UPDATES',
            'VIEWS_PALETTE',
            'VIEWS_PALETTE_WITH_PROPERTIES',
            'VIEWS_SHEET',
            'SOURCE',
            'SOURCE_COOLORS_ADD',
            'SOURCE_REALTIME_COLORS_ADD',
            'SOURCE_EXPLORE_ADD',
            'SOURCE_AI_REQUEST',
            'SOURCE_IMAGE_UPLOAD',
            'SOURCE_HARMONY_BASE',
            'SOURCE_HARMONY_ADD',
            'SOURCE_EXPLORE_ADD',
            'PRESETS_CUSTOM_ADD',
            'SCALE_CHROMA',
            'THEMES',
            'THEMES_NAME',
            'THEMES_PARAMS',
            'THEMES_DESCRIPTION',
            'COLORS',
            'COLORS_HUE_SHIFTING',
            'COLORS_CHROMA_SHIFTING',
            'COLORS_ALPHA',
            'COLORS_BACKGROUND_COLOR',
            'EXPORT_STYLESHEET_SCSS',
            'EXPORT_STYLESHEET_LESS',
            'EXPORT_TAILWIND_V3',
            'EXPORT_TAILWIND_V4',
            'EXPORT_APPLE_SWIFTUI',
            'EXPORT_APPLE_UIKIT',
            'EXPORT_ANDROID_COMPOSE',
            'EXPORT_ANDROID_XML',
            'EXPORT_CSV',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOPSIA',
          ],
          []
        ),
      },
    },
  },
  framer: {
    light: {
      framer: {
        env: {
          platform: 'framer',
          editor: 'framer',
          ui: 'framer',
          colorMode: 'framer-light',
        },
        features: doSpecificMode(
          ['LOCAL_PALETTES_PAGE'],
          [
            'LOCAL_PALETTES',
            'SYNC_LOCAL_STYLES',
            'SYNC_LOCAL_VARIABLES',
            'USER_PREFERENCES_SYNC_DEEP_STYLES',
            'USER_PREFERENCES_SYNC_DEEP_VARIABLES',
            'PREVIEW_LOCK_SOURCE_COLORS',
            'DOCUMENT_PALETTE',
            'DOCUMENT_PALETTE_PROPERTIES',
            'DOCUMENT_SHEET',
            'DOCUMENT_PUSH_UPDATES',
            'VIEWS_PALETTE',
            'VIEWS_PALETTE_WITH_PROPERTIES',
            'VIEWS_SHEET',
            'SOURCE',
            'SOURCE_COOLORS_ADD',
            'SOURCE_REALTIME_COLORS_ADD',
            'SOURCE_EXPLORE_ADD',
            'SOURCE_AI_REQUEST',
            'SOURCE_IMAGE_UPLOAD',
            'SOURCE_HARMONY_BASE',
            'SOURCE_HARMONY_ADD',
            'SOURCE_EXPLORE_ADD',
            'PRESETS_CUSTOM_ADD',
            'SCALE_CHROMA',
            'THEMES',
            'THEMES_NAME',
            'THEMES_PARAMS',
            'THEMES_DESCRIPTION',
            'COLORS',
            'COLORS_HUE_SHIFTING',
            'COLORS_CHROMA_SHIFTING',
            'COLORS_ALPHA',
            'COLORS_BACKGROUND_COLOR',
            'EXPORT_TAILWIND_V3',
            'EXPORT_TAILWIND_V4',
            'EXPORT_APPLE_SWIFTUI',
            'EXPORT_APPLE_UIKIT',
            'EXPORT_ANDROID_COMPOSE',
            'EXPORT_ANDROID_XML',
            'EXPORT_CSV',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOPSIA',
          ],
          []
        ),
      },
    },
    dark: {
      framer: {
        env: {
          platform: 'framer',
          editor: 'framer',
          ui: 'framer',
          colorMode: 'framer-dark',
        },
        features: doSpecificMode(
          ['LOCAL_PALETTES_PAGE'],
          [
            'LOCAL_PALETTES',
            'SYNC_LOCAL_STYLES',
            'SYNC_LOCAL_VARIABLES',
            'USER_PREFERENCES_SYNC_DEEP_STYLES',
            'USER_PREFERENCES_SYNC_DEEP_VARIABLES',
            'PREVIEW_LOCK_SOURCE_COLORS',
            'DOCUMENT_PALETTE',
            'DOCUMENT_PALETTE_PROPERTIES',
            'DOCUMENT_SHEET',
            'DOCUMENT_PUSH_UPDATES',
            'VIEWS_PALETTE',
            'VIEWS_PALETTE_WITH_PROPERTIES',
            'VIEWS_SHEET',
            'SOURCE',
            'SOURCE_COOLORS_ADD',
            'SOURCE_REALTIME_COLORS_ADD',
            'SOURCE_EXPLORE_ADD',
            'SOURCE_AI_REQUEST',
            'SOURCE_IMAGE_UPLOAD',
            'SOURCE_HARMONY_BASE',
            'SOURCE_HARMONY_ADD',
            'SOURCE_EXPLORE_ADD',
            'PRESETS_CUSTOM_ADD',
            'SCALE_CHROMA',
            'THEMES',
            'THEMES_NAME',
            'THEMES_PARAMS',
            'THEMES_DESCRIPTION',
            'COLORS',
            'COLORS_HUE_SHIFTING',
            'COLORS_CHROMA_SHIFTING',
            'COLORS_ALPHA',
            'COLORS_BACKGROUND_COLOR',
            'EXPORT_STYLESHEET_SCSS',
            'EXPORT_STYLESHEET_LESS',
            'EXPORT_TAILWIND_V3',
            'EXPORT_TAILWIND_V4',
            'EXPORT_APPLE_SWIFTUI',
            'EXPORT_APPLE_UIKIT',
            'EXPORT_ANDROID_COMPOSE',
            'EXPORT_ANDROID_XML',
            'EXPORT_CSV',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_PROTANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_TRITANOPIA',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOMALY',
            'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOPSIA',
          ],
          []
        ),
      },
    },
  },
}

const globalConfig: Config = {
  limits: {
    pageSize: 20,
    width: 640,
    height: 640,
    minWidth: 240,
    minHeight: 420,
    localPalettes: 1,
    sourceColors: 5,
    customStops: 8,
  },
  env: {
    ...specConfig[__PLATFORM__][__COLOR_MODE__][__EDITOR__].env,
    isDev,
    isSupabaseEnabled: import.meta.env.VITE_SUPABASE_ENABLED === 'true',
    isMixpanelEnabled: import.meta.env.VITE_MIXPANEL_ENABLED === 'true',
    isSentryEnabled: import.meta.env.VITE_SENTRY_ENABLED === 'true',
    isMistralAiEnabled: import.meta.env.VITE_MISTRAL_AI_ENABLED === 'true',
    announcementsDbId: import.meta.env.VITE_NOTION_ANNOUNCEMENTS_ID as string,
    onboardingDbId: import.meta.env.VITE_NOTION_ONBOARDING_ID as string,
    pluginId: '123456789',
  },
  plan: {
    isProEnabled: import.meta.env.VITE_PRO_ENABLED === 'true',
    isTrialEnabled: import.meta.env.VITE_TRIAL_ENABLED === 'true',
    trialTime: 72,
    creditsLimit: 200,
    creditsRenewalPeriodDays: 1,
    creditsRenewalPeriodHours: 24,
  },
  dbs: {
    palettesDbViewName: import.meta.env.VITE_DBS_PALETTES_VIEW as string,
    palettesDbTableName: import.meta.env.VITE_DBS_PALETTES_TABLE as string,
    starredPalettesDbTableName: import.meta.env
      .VITE_DBS_STARRED_PALETTES_TABLE as string,
  },
  urls: {
    authWorkerUrl: import.meta.env.VITE_AUTH_WORKER_URL as string,
    announcementsWorkerUrl: import.meta.env
      .VITE_ANNOUNCEMENTS_WORKER_URL as string,
    databaseUrl: import.meta.env.VITE_SUPABASE_URL as string,
    authUrl: import.meta.env.VITE_AUTH_URL as string,
    storeApiUrl: import.meta.env.VITE_LEMONSQUEEZY_URL as string,
    platformUrl: window.location.origin,
    uiUrl: import.meta.env.VITE_UI_URL as string,
    documentationUrl: 'https://uicp.ylb.lt/docs',
    repositoryUrl: 'https://uicp.ylb.lt/repository',
    communityUrl: 'https://uicp.ylb.lt/community',
    supportEmail: 'https://uicp.ylb.lt/contact',
    feedbackUrl:
      'https://angd.notion.site/ebd/13df8c62fd868018989de53f17ad6df3',
    trialFeedbackUrl: 'https://uicp.ylb.lt/feedback-trial',
    requestsUrl: 'https://uicp.ylb.lt/ideas',
    networkUrl: 'https://uicp.ylb.lt/network',
    authorUrl: 'https://uicp.ylb.lt/author',
    licenseUrl: 'https://uicp.ylb.lt/license',
    privacyUrl: 'https://uicp.ylb.lt/privacy',
    vsCodeFigmaPluginUrl:
      'https://marketplace.visualstudio.com/items?itemName=figma.figma-vscode-extension',
    isbUrl: 'https://isb.ylb.lt/website',
    uicpUrl: 'https://uicp.ylb.lt/website',
    storeUrl: 'https://uicp.ylb.lt/store',
    storeManagementUrl: 'https://uicp.ylb.lt/store-management',
    storeWithDiscountUrl: 'https://uicp.ylb.lt/store-discount',
    howToUseUrl: 'https://uicp.ylb.lt/how-to-use-figma',
  },
  versions: {
    userConsentVersion: '2024.01',
    trialVersion: '2024.04',
    algorithmVersion: 'v3',
    paletteVersion: '2025.06',
    pluginVersion: __APP_VERSION__,
    creditsVersion: '2025.12',
  },
  features: specConfig[__PLATFORM__][__COLOR_MODE__][__EDITOR__].features,
  lang: 'en-US',
  fees: {
    colourLoversImport: 50,
    coolorsImport: 50,
    realtimeColorsImport: 50,
    imageColorsExtract: 100,
    harmonyCreate: 100,
    aiColorsGenerate: 100,
    paletteGenerate: 50,
    paletteWithPropsGenerate: 75,
    sheetGenerate: 150,
    paletteUpdates: 20,
  },
}

const limitsMapping: { [key: string]: keyof typeof globalConfig.limits } = {
  LOCAL_PALETTES: 'localPalettes',
  SOURCE: 'sourceColors',
  COLORS: 'sourceColors',
  PRESETS_CUSTOM_ADD: 'customStops',
}

globalConfig.features.forEach((feature) => {
  const limitKey = limitsMapping[feature.name]
  if (limitKey && globalConfig.limits[limitKey] !== undefined)
    feature.limit = globalConfig.limits[limitKey]
})

export default globalConfig
